# Generated by Django 6.0.1 on 2026-02-12 05:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre del proyecto', max_length=120, unique=True)),
                ('description', models.TextField(blank=True, help_text='Descripcion del proyecto', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha de creacion del proyecto')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha de ultima actualizacion')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre unico de la etiqueta', max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha de creacion de la etiqueta')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha de ultima actualizacion')),
            ],
            options={
                'verbose_name': 'Etiqueta',
                'verbose_name_plural': 'Etiquetas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Titulo descriptivo de la tarea', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Descripcion detallada de la tarea', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('in_progress', 'En progreso'), ('completed', 'Completada'), ('archived', 'Archivada')], default='pending', help_text='Estado actual de la tarea', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta'), ('critical', 'Critica')], default='medium', help_text='Nivel de prioridad de la tarea', max_length=10)),
                ('due_date', models.DateTimeField(blank=True, help_text='Fecha limite para completar la tarea', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha de creacion de la tarea')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha de ultima actualizacion')),
                ('completed_at', models.DateTimeField(blank=True, help_text='Fecha en que se completo la tarea', null=True)),
                ('is_locked', models.BooleanField(default=False, help_text='Si es True, la tarea no puede ser modificada')),
                ('tags', models.CharField(blank=True, help_text='Etiquetas separadas por comas (ej: bug,urgent,backend)', max_length=500)),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Usuario asignado a la tarea', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks_assigned', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(help_text='Usuario que creo la tarea', on_delete=django.db.models.deletion.PROTECT, related_name='tasks_created', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, help_text='Proyecto al que pertenece la tarea', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='tasks.project')),
            ],
            options={
                'verbose_name': 'Tarea',
                'verbose_name_plural': 'Tareas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha de creacion de la relacion')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha de ultima actualizacion')),
                ('tag', models.ForeignKey(help_text='Etiqueta asociada', on_delete=django.db.models.deletion.CASCADE, related_name='task_tags', to='tasks.tag')),
                ('task', models.ForeignKey(help_text='Tarea asociada', on_delete=django.db.models.deletion.CASCADE, related_name='task_tags', to='tasks.task')),
            ],
            options={
                'verbose_name': 'Relacion Tarea-Etiqueta',
                'verbose_name_plural': 'Relaciones Tarea-Etiqueta',
            },
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['status'], name='tasks_task_status_4a0a95_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['assigned_to'], name='tasks_task_assigne_ab55af_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['created_by'], name='tasks_task_created_d80085_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['priority'], name='tasks_task_priorit_a900d4_idx'),
        ),
        migrations.AddConstraint(
            model_name='tasktag',
            constraint=models.UniqueConstraint(fields=('task', 'tag'), name='unique_task_tag'),
        ),
    ]
