# Generated by Django 6.0.1 on 2026-02-14 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudyTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre del tema de estudio', max_length=120, unique=True)),
                ('description', models.TextField(blank=True, help_text='Descripción breve del tema')),
                ('difficulty', models.CharField(choices=[('beginner', 'Principiante'), ('intermediate', 'Intermedio'), ('advanced', 'Avanzado')], default='beginner', help_text='Nivel sugerido de dificultad', max_length=15)),
                ('is_active', models.BooleanField(default=True, help_text='Permite ocultar un tema sin borrarlo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tema de estudio',
                'verbose_name_plural': 'Temas de estudio',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StudyBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(help_text='Orden dentro del tema (1, 2, 3...).')),
                ('title', models.CharField(help_text='Título del bloque', max_length=120)),
                ('description', models.TextField(blank=True, help_text='Descripción del bloque')),
                ('estimated_minutes', models.PositiveSmallIntegerField(default=30, help_text='Tiempo estimado de estudio')),
                ('is_published', models.BooleanField(default=True, help_text='Si es falso, el bloque no se expone')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('topic', models.ForeignKey(help_text='Tema al que pertenece el bloque', on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='tasks.studytopic')),
            ],
            options={
                'verbose_name': 'Bloque',
                'verbose_name_plural': 'Bloques',
                'ordering': ['topic', 'number'],
            },
        ),
        migrations.CreateModel(
            name='BlockTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Título de la tarea', max_length=200)),
                ('instructions', models.TextField(help_text='Instrucciones de la tarea')),
                ('resources', models.JSONField(blank=True, help_text='Lista o diccionario de recursos (links, IDs de material, etc.)', null=True)),
                ('estimated_minutes', models.PositiveSmallIntegerField(default=15, help_text='Tiempo estimado para completar')),
                ('order', models.PositiveSmallIntegerField(default=1, help_text='Posición dentro del bloque')),
                ('status', models.CharField(choices=[('available', 'Disponible'), ('archived', 'Archivada')], default='available', help_text='Estado de publicación de la tarea', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('block', models.ForeignKey(help_text='Bloque al que pertenece la tarea', on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='tasks.studyblock')),
            ],
            options={
                'verbose_name': 'Tarea de bloque',
                'verbose_name_plural': 'Tareas de bloque',
                'ordering': ['block', 'order', '-created_at'],
                'indexes': [models.Index(fields=['block', 'order'], name='tasks_block_block_i_535d90_idx'), models.Index(fields=['status'], name='tasks_block_status_7c3075_idx')],
                'unique_together': {('block', 'order')},
            },
        ),
        migrations.AddIndex(
            model_name='studyblock',
            index=models.Index(fields=['topic', 'number'], name='tasks_study_topic_i_bd3980_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='studyblock',
            unique_together={('topic', 'number')},
        ),
    ]
