# Generated by Django 6.0.1 on 2026-01-27 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Título descriptivo de la tarea', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Descripción detallada de la tarea', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('in_progress', 'En progreso'), ('completed', 'Completada'), ('archived', 'Archivada')], default='pending', help_text='Estado actual de la tarea', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta'), ('critical', 'Crítica')], default='medium', help_text='Nivel de prioridad de la tarea', max_length=10)),
                ('due_date', models.DateTimeField(blank=True, help_text='Fecha límite para completar la tarea', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación de la tarea')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha de última actualización')),
                ('completed_at', models.DateTimeField(blank=True, help_text='Fecha en que se completó la tarea', null=True)),
                ('is_locked', models.BooleanField(default=False, help_text='Si es True, la tarea no puede ser modificada')),
                ('tags', models.CharField(blank=True, help_text='Etiquetas separadas por comas (ej: bug,urgent,backend)', max_length=500)),
            ],
            options={
                'verbose_name': 'Tarea',
                'verbose_name_plural': 'Tareas',
                'ordering': ['-created_at'],
            },
        ),
    ]
