# Generated by Django 6.0.1 on 2026-01-30 04:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_task_completed_at_alter_task_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre del proyecto', max_length=120, unique=True)),
                ('description', models.TextField(blank=True, help_text='Descripcion del proyecto', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha de creacion del proyecto')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha de ultima actualizacion')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre unico de la etiqueta', max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha de creacion de la etiqueta')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha de ultima actualizacion')),
            ],
            options={
                'verbose_name': 'Etiqueta',
                'verbose_name_plural': 'Etiquetas',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='task',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Proyecto al que pertenece la tarea', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='tasks.project'),
        ),
        migrations.CreateModel(
            name='TaskTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha de creacion de la relacion')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha de ultima actualizacion')),
                ('tag', models.ForeignKey(help_text='Etiqueta asociada', on_delete=django.db.models.deletion.CASCADE, related_name='task_tags', to='tasks.tag')),
                ('task', models.ForeignKey(help_text='Tarea asociada', on_delete=django.db.models.deletion.CASCADE, related_name='task_tags', to='tasks.task')),
            ],
            options={
                'verbose_name': 'Relacion Tarea-Etiqueta',
                'verbose_name_plural': 'Relaciones Tarea-Etiqueta',
                'constraints': [models.UniqueConstraint(fields=('task', 'tag'), name='unique_task_tag')],
            },
        ),
    ]
